#!/usr/bin/env bash
# HomeClaw release pipeline on the App Store Connect CLI (`asc`).
#
# Replaces the old Fastlane lanes (Fastfile/Gymfile/Appfile), which in turn had
# replaced scripts/archive.sh and scripts/asc-testflight.py. Every guardrail
# those had is carried over below, with the incident that motivated it.
#
#   scripts/release.sh help
#
# HomeClaw ships one product: the Mac Catalyst app (bundle com.shahine.homeclaw)
# on the Mac App Store, with homeclaw-cli, macOSBridge.bundle, mcp-server.js and
# the OpenClaw plugin embedded in it. There is no iOS App Store listing and no
# Developer ID build (the HomeKit entitlement is App Store-only on macOS).
#
# TestFlight is not App Store submission. `beta` uploads to TestFlight and
# stops. Only `release` and `submit` send anything to App Review, and nothing
# here chains `beta` into them.
#
# Adapting this file to another app: edit the CONFIG block, then the functions
# marked "REPO-SPECIFIC". Everything else is generic.
set -euo pipefail

# ─── CONFIG ──────────────────────────────────────────────────────────────
APP_ID="6759682551"
APP_NAME="HomeClaw"
PROJECT="HomeClaw.xcodeproj"              # generated by xcodegen from project.yml (gitignored)
WORKSPACE=""
SCHEME="HomeClaw"
PLATFORM="MAC_OS"                         # asc platform: IOS | MAC_OS
# Mac Catalyst archive: required for HomeKit entitlement support on macOS.
DESTINATION="generic/platform=macOS,variant=Mac Catalyst"
TEAM_ID_VARS="HOMEKIT_TEAM_ID APPLE_TEAM_ID"  # first one set wins
# Profiles the export signs with manually, one "<bundle id>=<profile name>"
# per line; the name must match the target's PROVISIONING_PROFILE_SPECIFIER.
# Downloaded fresh on every beta run; `profiles --repair` regenerates them.
PROFILES="
com.shahine.homeclaw=com.shahine.homeclaw AppStore
"
# A Catalyst app's App Store profile is MAC_CATALYST_APP_STORE, not
# MAC_APP_STORE (that is for native AppKit apps).
PROFILE_TYPE="MAC_CATALYST_APP_STORE"
# The profile embeds an Apple Distribution certificate (type DISTRIBUTION),
# the same kind iOS uses; there is no separate Mac app certificate here.
DIST_CERT_TYPE="DISTRIBUTION"             # certificate type repair signs new profiles with
SIGNING_CERT="Apple Distribution"         # ExportOptions signingCertificate
# The Mac .pkg is signed twice: the app with Apple Distribution, the installer
# package with this certificate. (The old lane minted it with
# `fastlane run cert type:mac_installer_distribution`.)
INSTALLER_CERT="3rd Party Mac Developer Installer"
INTERNAL_GROUP="Internal Testers"
EXTERNAL_GROUP="External Testers"
LOCALE="en-US"
# automatic_release: false in the old lanes: after approval the version waits
# in "Pending Developer Release" until you ship it. `release --auto-release`
# switches a run to AFTER_APPROVAL.
RELEASE_TYPE="MANUAL"
# App Store screenshot display types by capture size (WIDTHxHEIGHT=TYPE).
# Every Mac size ASC accepts maps to the one desktop set.
SCREENSHOT_TYPES="2880x1800=APP_DESKTOP 2560x1600=APP_DESKTOP 1440x900=APP_DESKTOP 1280x800=APP_DESKTOP"
# Marketing version and build number live in this plist (see marketing_version).
INFO_PLIST="Resources/Info.plist"
# ─────────────────────────────────────────────────────────────────────────

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APPSTORE_DIR="$REPO_ROOT/appstore"
METADATA_DIR="$APPSTORE_DIR/metadata"
SHOTS_DIR="$APPSTORE_DIR/screenshots"
FRAMED_DIR="$APPSTORE_DIR/framed"
ARTIFACTS="$REPO_ROOT/.asc/artifacts"
ARCHIVE_PATH="$ARTIFACTS/$SCHEME.xcarchive"
# iOS exports an .ipa, macOS a .pkg; asc takes a different flag for each.
if [[ "$PLATFORM" == "MAC_OS" ]]; then
  PACKAGE_PATH="$ARTIFACTS/$SCHEME.pkg" PACKAGE_KIND="pkg" PACKAGE_LABEL="PKG" PROFILE_EXT="provisionprofile"
else
  PACKAGE_PATH="$ARTIFACTS/$SCHEME.ipa" PACKAGE_KIND="ipa" PACKAGE_LABEL="IPA" PROFILE_EXT="mobileprovision"
fi
# Framing and staging need Pillow, which lives in Homebrew's Python, not
# /usr/bin/python3 (and /usr/bin goes first on PATH below).
if [[ -z "${PYTHON:-}" ]]; then
  PYTHON=python3
  [[ -x /opt/homebrew/bin/python3 ]] && PYTHON=/opt/homebrew/bin/python3
fi

# Xcode's exportArchive step shells out to `rsync` and only works with the
# system binary; a Homebrew rsync (3.4.x) earlier on PATH makes export fail
# with an opaque "Copy failed". Put /usr/bin first for everything below.
case "$PATH" in /usr/bin:*) ;; *) PATH="/usr/bin:$PATH" ;; esac
# A bare environment (cron, launchd, `env -i`) has no Homebrew on PATH; asc,
# xcodegen and node live there. Appended, so it never shadows the system rsync.
case ":$PATH:" in *:/opt/homebrew/bin:*) ;; *) PATH="$PATH:/opt/homebrew/bin" ;; esac
export PATH

# ─── Output helpers ──────────────────────────────────────────────────────

bold() { printf '\033[1m%s\033[0m\n' "$*"; }
step() { printf '\n\033[1;34m==>\033[0m \033[1m%s\033[0m\n' "$*"; }
info() { printf '    %s\n' "$*"; }
warn() { printf '\033[33mwarning:\033[0m %s\n' "$*" >&2; }
die() { printf '\033[31merror:\033[0m %s\n' "$*" >&2; exit 1; }

# json_get '<python expression over d>' < json — tiny jq substitute that
# ships with macOS. Prints nothing (not "None") for a missing value.
json_get() {
  "$PYTHON" -c 'import json,sys
d=json.load(sys.stdin)
v=eval(sys.argv[1])
print("" if v is None else v)' "$1"
}

# ─── Credentials ─────────────────────────────────────────────────────────
#
# asc reads ASC_KEY_ID / ASC_ISSUER_ID / ASC_PRIVATE_KEY_PATH. An interactive
# shell already has them from ~/.zshrc; otherwise fall back to the chezmoi
# secrets file (canonical APP_STORE_CONNECT_API_* names) and then the repo's
# .env.local (per-project ASC_* / *_TEAM_ID overrides). Values are never
# printed. The macOS Keychain is never used (ASC_BYPASS_KEYCHAIN=1).
load_credentials() {
  if [[ -z "${ASC_KEY_ID:-}" ]]; then
    local secrets="$HOME/.secrets-macbook-pro.env"
    # shellcheck source=/dev/null
    [[ -f "$secrets" ]] && source "$secrets"
    # shellcheck source=/dev/null
    [[ -f "$REPO_ROOT/.env.local" ]] && source "$REPO_ROOT/.env.local"
    ASC_KEY_ID="${ASC_KEY_ID:-${APP_STORE_CONNECT_API_KEY_ID:-}}"
    ASC_ISSUER_ID="${ASC_ISSUER_ID:-${APP_STORE_CONNECT_API_ISSUER_ID:-}}"
  fi
  if [[ -z "${ASC_PRIVATE_KEY_PATH:-}" ]]; then
    # ASC_KEY_PATH is the name the old Fastfile/.env.local used.
    if [[ -n "${ASC_KEY_PATH:-}" ]]; then
      ASC_PRIVATE_KEY_PATH="$ASC_KEY_PATH"
    elif [[ -f "$HOME/.private_keys/AuthKey_${ASC_KEY_ID:-}.p8" ]]; then
      ASC_PRIVATE_KEY_PATH="$HOME/.private_keys/AuthKey_${ASC_KEY_ID}.p8"
    elif [[ "${ASC_KEY_ID:-}" == "${APP_STORE_CONNECT_API_KEY_ID:-}" ]]; then
      ASC_PRIVATE_KEY_PATH="${APP_STORE_CONNECT_API_KEY_PATH:-}"
    fi
  fi
  [[ -n "${ASC_KEY_ID:-}" && -n "${ASC_ISSUER_ID:-}" ]] \
    || die "App Store Connect API key not configured (ASC_KEY_ID/ASC_ISSUER_ID or APP_STORE_CONNECT_API_KEY_ID/_ISSUER_ID)."
  [[ -f "${ASC_PRIVATE_KEY_PATH:-}" ]] || die "App Store Connect .p8 key not found (set ASC_PRIVATE_KEY_PATH)."
  export ASC_KEY_ID ASC_ISSUER_ID ASC_PRIVATE_KEY_PATH
  export ASC_BYPASS_KEYCHAIN=1 ASC_TELEMETRY_DISABLED=1

  # The repo's .env.local carries its own *_TEAM_ID. When ~/.zshrc already
  # exported the ASC_* key it isn't sourced above, so read only the team-id
  # names from it in a subshell; the key pairing exported above stays intact.
  TEAM_ID="" TEAM_ID_SOURCE=""
  local var value
  for var in $TEAM_ID_VARS; do
    value="${!var:-}"
    if [[ -z "$value" && -f "$REPO_ROOT/.env.local" ]]; then
      # shellcheck source=/dev/null
      value=$(source "$REPO_ROOT/.env.local" >/dev/null 2>&1; printf '%s' "${!var:-}")
    fi
    # .env.local.example ships HOMEKIT_TEAM_ID=YOUR_TEAM_ID; that is unset.
    [[ "$value" == "YOUR_TEAM_ID" ]] && value=""
    if [[ -n "$value" ]]; then TEAM_ID="$value" TEAM_ID_SOURCE="$var"; break; fi
  done
}

# Every read-only or --dry-run path runs with ASC_READ_ONLY=1, so asc refuses
# any POST/PATCH/PUT/DELETE before it is sent, even if a flag is wrong here.
read_only() { export ASC_READ_ONLY=1; }

# ─── Project facts ───────────────────────────────────────────────────────

plist_value() { /usr/libexec/PlistBuddy -c "Print :$1" "$REPO_ROOT/$INFO_PLIST"; }

# REPO-SPECIFIC: HomeClaw's marketing version comes from the nearest `v*` git
# tag, not the project: release tags are `v{version}+{build}` and Apple
# rejects the extra component, so the `+build` suffix is stripped. project.yml's
# archive pre-build script derives CFBundleShortVersionString the same way, so
# a new version starts with `git tag -a v1.0.13` (scripts/bump-version.sh).
marketing_version() {
  local tag
  tag=$(git -C "$REPO_ROOT" describe --tags --abbrev=0 --match 'v*' 2>/dev/null || true)
  tag="${tag:-v0.0.1}"
  tag="${tag#v}"
  printf '%s\n' "${tag%%+*}"
}

# REPO-SPECIFIC: the build number is CFBundleVersion as committed in
# Resources/Info.plist. `bump-build` writes the next one; commit it
# ("chore(release): build N") and tag v{version}+N before `beta`.
build_number() { plist_value CFBundleVersion; }

# TestFlight "What to Test" defaults to the App Store release notes so it
# can't drift from the metadata (override with TF_CHANGELOG).
tester_notes() {
  if [[ -n "${TF_CHANGELOG:-}" ]]; then
    printf '%s' "$TF_CHANGELOG"
  elif [[ -f "$METADATA_DIR/$LOCALE/release_notes.txt" ]]; then
    sed -e 's/[[:space:]]*$//' "$METADATA_DIR/$LOCALE/release_notes.txt"
  else
    printf 'Bug fixes and improvements.'
  fi
}

# ─── Guardrails ──────────────────────────────────────────────────────────

# A release artifact has to be reproducible from a committed revision.
# Build 20 of SendTimes 1.1 reached TestFlight from a dirty tree and no commit
# anywhere carried that build number, so the uploaded binary could never be
# tied back to a source revision. HomeClaw's old lanes archived first and
# committed the bumped Info.plist afterwards, which had the same gap.
require_clean_tree() {
  local dirty
  # A failed `git` would otherwise return "" and read as a clean tree.
  dirty=$(git -C "$REPO_ROOT" status --porcelain) \
    || die "could not read worktree state (git exited $?); refusing to build."
  if [[ -n "$dirty" ]]; then
    printf '%s\n' "$dirty" >&2
    die "worktree is dirty. Commit or stash before cutting a release build."
  fi
}

# REPO-SPECIFIC: resolve the Xcode to archive with, and say which one it was.
#
# A machine with several Xcodes installed otherwise archives against whatever
# `xcode-select` points at, invisibly — a release built on the wrong toolchain
# is not something to discover from App Store Connect. Resolution order:
# DEVELOPER_DIR, XCODE_APP, .xcode-version, xcode-select. Betas and release
# builds live side by side, so .xcode-version is matched on
# CFBundleShortVersionString, not the app name.
resolve_toolchain() {
  local pin="" app installed=() version
  [[ -f "$REPO_ROOT/.xcode-version" ]] && pin=$(tr -d '[:space:]' <"$REPO_ROOT/.xcode-version")
  if [[ -z "${DEVELOPER_DIR:-}" && -n "${XCODE_APP:-}" ]]; then
    DEVELOPER_DIR="$XCODE_APP/Contents/Developer"
  fi
  if [[ -z "${DEVELOPER_DIR:-}" && -n "$pin" ]]; then
    for app in /Applications/Xcode*.app; do
      version=$(defaults read "$app/Contents/Info.plist" CFBundleShortVersionString 2>/dev/null || echo '?')
      installed+=("$app ($version)")
      if [[ "$version" == "$pin" ]]; then DEVELOPER_DIR="$app/Contents/Developer"; break; fi
    done
    [[ -n "${DEVELOPER_DIR:-}" ]] || die ".xcode-version pins Xcode $pin, but no installed Xcode reports that version.
Installed: ${installed[*]}
Install it, or override for this run: XCODE_APP=/Applications/Xcode.app scripts/release.sh <command>"
  fi
  if [[ -n "${DEVELOPER_DIR:-}" ]]; then
    [[ -d "$DEVELOPER_DIR" ]] || die "DEVELOPER_DIR does not exist: $DEVELOPER_DIR"
    export DEVELOPER_DIR
  fi
  version=$(xcodebuild -version | head -n 1)
  info "Toolchain: $version ($(xcode-select -p))"
  [[ -z "$pin" || "$version" == *"$pin"* ]] || warn "toolchain $version does not match .xcode-version pin $pin"
}

# App Review rejects binaries built with a beta Xcode ("The build's Xcode build
# is not supported yet"), but only at submission time: the upload and
# TestFlight processing both succeed, so the build looks fine until it
# silently cannot be submitted. Build 23 of SendTimes 1.1 was lost this way
# when xcode-select pointed at Xcode-beta 27.0. `xcode-select -p` honors
# DEVELOPER_DIR, so a per-invocation override works:
#   DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer scripts/release.sh beta
require_release_xcode() {
  local developer_dir version build
  developer_dir=$(xcode-select -p)
  version=$(xcodebuild -version | head -n 1)
  build=$(xcodebuild -version | sed -n 's/^Build version //p')
  # Only the app path is a reliable signal: GA build numbers also end in a
  # letter (16A242d) and some GA builds use beta-style numbers (16C5032a).
  if [[ "$developer_dir" == *Xcode-beta* ]]; then
    die "the active Xcode is a beta ($developer_dir, $version, $build).
App Review will not accept a build made with it. Switch with:
  sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
or set DEVELOPER_DIR (or .xcode-version) for this invocation."
  fi
  info "Building with $version ($build) at $developer_dir"
}

# REPO-SPECIFIC: concurrent xcodebuild runs against the same project can wedge
# the build service: a run sits at the toolchain probe producing nothing, which
# reads as a broken toolchain rather than contention. Fail fast instead of
# hanging a release. Scoped to this project; unrelated builds are allowed.
ensure_no_concurrent_build() {
  local pids
  pids=$(pgrep -f "xcodebuild.*$APP_NAME.xcodeproj" 2>/dev/null || true)
  [[ -z "$pids" ]] || die "another xcodebuild is already running against $APP_NAME.xcodeproj (pid ${pids%%$'\n'*}). Concurrent builds wedge the build service. Wait for it to finish, or kill it."
}

# Release integrity: tag before you upload (see AGENTS.md). The build-bump
# commit carries a vX.Y[.Z] or vX.Y[.Z]+BUILD tag, HEAD is that commit, and it
# is pushed. A tag is the only record of which source a shipped binary came
# from. With --dry-run a failure is reported, not fatal, so the build path can
# still be verified from an untagged commit.
check_release_tag() {
  local soft="$1" version build tag tag_version tag_build problems=()
  version=$(marketing_version)
  build=$(build_number)
  # Prefer a vX.Y.Z+BUILD tag when HEAD carries several.
  tag=$(git -C "$REPO_ROOT" tag --points-at HEAD --list 'v*' | sort -t+ -k2 -n | tail -n 1)
  if [[ -z "$tag" ]]; then
    problems+=("HEAD has no v* release tag. Tag the build-bump commit (v$version+$build) before uploading.")
  elif [[ ! "$tag" =~ ^v([0-9]+\.[0-9]+(\.[0-9]+)?)(\+([0-9]+))?$ ]]; then
    problems+=("tag '$tag' is not vX.Y.Z or vX.Y.Z+BUILD.")
  else
    tag_version="${BASH_REMATCH[1]}"
    tag_build="${BASH_REMATCH[4]}"
    [[ "$tag_version" == "$version" ]] \
      || problems+=("tag $tag says version $tag_version but the project says $version.")
    [[ -z "$tag_build" || "$tag_build" == "$build" ]] \
      || problems+=("tag $tag says build $tag_build but the project says $build.")
  fi
  # REPO-SPECIFIC: the archive pre-build script rewrites Info.plist's short
  # version from the tag. If the committed plist disagrees, the archive dirties
  # the tree with a version no commit carries (`bump-build` syncs both).
  local plist_version
  plist_version=$(plist_value CFBundleShortVersionString)
  [[ "$plist_version" == "$version" ]] \
    || problems+=("$INFO_PLIST says version $plist_version but the nearest tag says $version. Run: scripts/release.sh bump-build")
  if [[ -z "$(git -C "$REPO_ROOT" branch -r --contains HEAD 2>/dev/null)" ]]; then
    problems+=("HEAD is not on any remote branch. Push the release commit before uploading.")
  fi
  local p
  for p in ${problems[@]+"${problems[@]}"}; do
    if [[ "$soft" == "soft" ]]; then warn "upload would refuse: $p"; else die "$p"; fi
  done
  [[ ${#problems[@]} -gt 0 ]] || info "Release tag $tag matches $version ($build) and HEAD is pushed"
}

# REPO-SPECIFIC: the build-number write-back.
#
# In SendTimes, Xcode 26+ bumps CURRENT_PROJECT_VERSION in project.pbxproj as
# a side effect of `archive`. HomeClaw's project is generated and gitignored;
# here the writer is project.yml's "Increment Build Number (Archive Only)"
# pre-build script, which sets CFBundleVersion in Resources/Info.plist to
# `.build-number` + 1 (and CFBundleShortVersionString from the tag). Seeding
# `.build-number` with the committed build minus one makes that script land on
# the committed number, so the archive is built with exactly what HEAD says.
# The plist is still snapshotted and put back on success AND failure: the
# archive can succeed and the export then fail (stale profiles, the Homebrew
# rsync issue above), which is exactly how an unbuilt build number used to be
# left behind. Restoring the whole file is safe because beta refuses to start
# against a dirty tree, so any difference is the build's own edit.
VERSION_FILE="$REPO_ROOT/$INFO_PLIST"
VERSION_SNAPSHOT="$ARTIFACTS/Info.plist.before-archive"
SNAPSHOT_ACTIVE=false
snapshot_version_file() {
  cp "$VERSION_FILE" "$VERSION_SNAPSHOT"
  SNAPSHOT_ACTIVE=true
  trap restore_version_file EXIT
  printf '%s\n' "$(($(build_number) - 1))" >"$REPO_ROOT/.build-number"
}
restore_version_file() {
  $SNAPSHOT_ACTIVE || return 0
  SNAPSHOT_ACTIVE=false
  if ! cmp -s "$VERSION_SNAPSHOT" "$VERSION_FILE"; then
    cp "$VERSION_SNAPSHOT" "$VERSION_FILE"
    info "Reverted the archive's edit to $INFO_PLIST; it still reads the build that was archived."
  fi
}

# REPO-SPECIFIC: pre-archive prep. Regenerate the Xcode project and build the
# Node.js MCP server that gets bundled into the app.
prepare() {
  command -v xcodegen >/dev/null || die "xcodegen not installed. brew install xcodegen"
  ensure_no_concurrent_build

  step "Generate Xcode project"
  logged xcodegen xcodegen generate --use-cache --spec "$REPO_ROOT/project.yml" --project "$REPO_ROOT"

  # npm ci, not the existing node_modules: a stale install silently bundles
  # different dependency versions into the shipped mcp-server.js (build 196
  # shipped MCP SDK 1.27.1 against a 1.30.0 lockfile).
  step "Install locked npm dependencies and build the MCP server"
  logged npm-ci npm ci --no-audit --no-fund
  logged build-mcp npm run build:mcp

  # The bundle goes into the app, so it must match the committed source.
  local dist="mcp-server/dist/server.js"
  git -C "$REPO_ROOT" diff --quiet HEAD -- "$dist" \
    || die "$dist differs from the committed bundle after a clean build. Commit the rebuilt bundle (via PR) before releasing."

  # Without the HomeKit entitlement HMHomeManager silently returns zero homes.
  grep -q "com.apple.developer.homekit" "$REPO_ROOT/Resources/HomeClaw.entitlements" \
    || die "HomeKit entitlement missing from Resources/HomeClaw.entitlements."
}

# ─── Signing ─────────────────────────────────────────────────────────────
#
# Export with manual signing against freshly fetched App Store profiles.
# Xcode's cached automatic "iOS Team Store Provisioning Profile" entries can
# lag behind the current Apple Distribution certificate and make exportArchive
# fail with "doesn't include signing certificate". Downloading is read-only on
# the developer account. A profile goes INVALID when its bundle ID's
# capabilities change; fastlane's sigh used to regenerate it silently on every
# build. Here that is a separate, explicit step (`profiles --repair`) so a
# build never changes the developer account behind your back.
EXPORT_OPTIONS="$ARTIFACTS/ExportOptions.plist"

# "<bundle id><TAB><profile name>" per configured profile.
profile_entries() {
  local line
  while IFS= read -r line; do
    [[ -n "${line// /}" ]] || continue
    printf '%s\t%s\n' "${line%%=*}" "${line#*=}"
  done <<<"$PROFILES"
}

refresh_profiles() {
  local dirs=("$HOME/Library/Developer/Xcode/UserData/Provisioning Profiles")
  # iOS tooling still reads the legacy MobileDevice folder; macOS doesn't.
  [[ "$PROFILE_EXT" == "mobileprovision" ]] && dirs+=("$HOME/Library/MobileDevice/Provisioning Profiles")
  local signing_dir bundle name json id uuid file
  mkdir -p "$ARTIFACTS" "${dirs[@]}"
  # A fresh folder per run: `asc profiles download` won't overwrite a file.
  signing_dir=$(mktemp -d "$ARTIFACTS/signing.XXXXXX")
  plutil -create xml1 "$EXPORT_OPTIONS"
  /usr/libexec/PlistBuddy \
    -c "Add :method string app-store-connect" \
    -c "Add :destination string export" \
    -c "Add :signingStyle string manual" \
    -c "Add :signingCertificate string $SIGNING_CERT" \
    -c "Add :teamID string $TEAM_ID" \
    -c "Add :uploadSymbols bool true" \
    -c "Add :manageAppVersionAndBuildNumber bool false" \
    -c "Add :provisioningProfiles dict" \
    "$EXPORT_OPTIONS" >/dev/null
  if [[ -n "$INSTALLER_CERT" ]]; then
    /usr/libexec/PlistBuddy -c "Add :installerSigningCertificate string $INSTALLER_CERT" "$EXPORT_OPTIONS" >/dev/null
  fi
  while IFS=$'\t' read -r bundle name; do
    # `--name` is not an exact match: it also returns the timestamp-suffixed
    # copies `sigh --force` left behind ("<name> 1787293412"), and data[0] can
    # be one of those. The archive's PROVISIONING_PROFILE_SPECIFIER wants the
    # exact name, so match it exactly and take the newest.
    json=$(asc profiles list --name "$name" --profile-type "$PROFILE_TYPE" --profile-state ACTIVE --paginate --output json)
    id=$(NAME="$name" json_get 'max((p for p in d.get("data") or [] if p["attributes"]["name"] == __import__("os").environ["NAME"]), key=lambda p: p["attributes"].get("expirationDate") or "", default={}).get("id")' <<<"$json")
    [[ -n "$id" ]] || die "no ACTIVE $PROFILE_TYPE profile named '$name'. Run: scripts/release.sh profiles --repair"
    file="$signing_dir/$bundle.$PROFILE_EXT"
    asc profiles download --id "$id" --output "$file" >/dev/null
    require_profile_certificate "$file" "$name"  # REPO-SPECIFIC
    uuid=$(asc profiles inspect --path "$file" --output json | json_get 'd.get("uuid") or d.get("UUID")')
    [[ -n "$uuid" ]] || uuid=$(security cms -D -i "$file" | plutil -extract UUID raw -o - -)
    local d
    for d in "${dirs[@]}"; do cp "$file" "$d/$uuid.$PROFILE_EXT"; done
    /usr/libexec/PlistBuddy -c "Add :provisioningProfiles:$bundle string $uuid" "$EXPORT_OPTIONS" >/dev/null
    info "$bundle -> profile $uuid"
  done < <(profile_entries)
}

# Check (default), repair, or prune the configured profiles.
#   profiles                  read-only report
#   profiles --repair         for each profile with no ACTIVE copy: delete the
#                             INVALID one holding the name (names are unique,
#                             and an INVALID profile can't be used), then create
#                             a fresh one against the newest $DIST_CERT_TYPE cert
#   profiles --prune          also delete INVALID "<name> <timestamp>" copies
#                             that sigh --force left behind
#   --dry-run                 print the plan, change nothing
cmd_profiles() {
  local repair=false prune=false dry_run=false
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --repair) repair=true ;;
      --prune) prune=true ;;
      --dry-run) dry_run=true ;;
      *) die "unknown profiles option: $1" ;;
    esac
    shift
  done
  load_credentials
  if $dry_run || ! { $repair || $prune; }; then read_only; fi
  step "$PROFILE_TYPE profiles$($repair && echo ' (repair)')$($prune && echo ' (prune)')$($dry_run && echo ' [dry run]')"
  PROFILE_LINES="$(profile_entries)" "$PYTHON" - "$PROFILE_TYPE" "$DIST_CERT_TYPE" "$repair" "$prune" "$dry_run" <<'PY'
import json, re, subprocess, sys
ptype, cert_type = sys.argv[1], sys.argv[2]
repair, prune, dry = (a == "true" for a in sys.argv[3:6])

def asc(*args):
    out = subprocess.run(["asc", *args, "--output", "json"], check=True, capture_output=True, text=True).stdout
    return json.loads(out) if out.strip() else {}

def cert_id():
    certs = [c for c in asc("certificates", "list", "--paginate")["data"]
             if c["attributes"].get("certificateType") == cert_type]
    if not certs:
        sys.exit(f"no {cert_type} certificate on the account")
    return max(certs, key=lambda c: c["attributes"].get("expirationDate") or "")["id"]

failed = False
cert = None
import os
for line in os.environ["PROFILE_LINES"].splitlines():
    bundle, name = line.split("\t", 1)
    profiles = asc("profiles", "list", "--name", name, "--profile-type", ptype, "--paginate").get("data") or []
    exact = [p for p in profiles if p["attributes"]["name"] == name]
    leftovers = [p for p in profiles if re.fullmatch(re.escape(name) + r" \d{9,}", p["attributes"]["name"])]
    active = [p for p in exact if p["attributes"].get("profileState") == "ACTIVE"]
    invalid = [p for p in exact if p["attributes"].get("profileState") != "ACTIVE"]
    stale = [p for p in leftovers if p["attributes"].get("profileState") != "ACTIVE"]
    status = "ACTIVE" if active else ("INVALID" if invalid else "MISSING")
    print(f"    {name}: {status}" + (f", {len(stale)} stale sigh copies" if stale else ""))
    actions = []
    if not active and repair:
        actions += [("delete", p) for p in invalid] + [("create", None)]
    elif not active:
        failed = True
    if prune:
        actions += [("delete", p) for p in stale]
    for verb, p in actions:
        label = f'{p["attributes"]["name"]} ({p["id"]})' if p else name
        if dry:
            print(f"      would {verb} {label}")
            continue
        if verb == "delete":
            asc("profiles", "delete", "--id", p["id"], "--confirm")
        else:
            cert = cert or cert_id()
            bid = [b for b in asc("bundle-ids", "list", "--identifier", bundle, "--paginate")["data"]
                   if b["attributes"]["identifier"] == bundle]
            if not bid:
                sys.exit(f"bundle id {bundle} is not registered")
            asc("profiles", "create", "--name", name, "--profile-type", ptype,
                "--bundle", bid[0]["id"], "--certificate", cert)
        print(f"      {verb}d {label}")
if failed:
    sys.exit("some profiles have no ACTIVE copy; run: scripts/release.sh profiles --repair")
PY
}

# REPO-SPECIFIC (from the old Fastfile's profile resolver): a profile minted on
# another Mac embeds that machine's distribution certificate. Exporting with it
# fails on a certificate mismatch, so require that one of the profile's
# embedded certificates is installed here. DeveloperCertificates holds DER
# blobs whose SHA-1 is the fingerprint `security find-identity` prints (this
# lists identities; it reads no secrets).
require_profile_certificate() {
  local file="$1" name="$2" local_ids
  local_ids=$(security find-identity -v -p codesigning | grep -oE '\b[0-9A-F]{40}\b' | sort -u)
  security cms -D -i "$file" | "$PYTHON" -c '
import hashlib, plistlib, sys
local = set(sys.argv[1].split())
certs = plistlib.loads(sys.stdin.buffer.read()).get("DeveloperCertificates", [])
sys.exit(0 if any(hashlib.sha1(c).hexdigest().upper() in local for c in certs) else 1)
' "$local_ids" || die "profile '$name' is signed for a certificate that is not in this keychain. Regenerate it for this Mac's Apple Distribution certificate."
}

# ─── Build ───────────────────────────────────────────────────────────────

# Runs a noisy build step with its output in .asc/logs/<name>.log, showing
# the tail only when it fails.
logged() {
  local name="$1" log="$REPO_ROOT/.asc/logs/$1.log"
  shift
  mkdir -p "$(dirname "$log")"
  if ! "$@" >"$log" 2>&1; then
    tail -n 40 "$log" >&2
    die "$name failed. Full log: $log"
  fi
  info "log: .asc/logs/$name.log"
}

archive_only() {
  local container=(--project "$REPO_ROOT/$PROJECT")
  [[ -n "$WORKSPACE" ]] && container=(--workspace "$REPO_ROOT/$WORKSPACE")
  mkdir -p "$ARTIFACTS"

  step "Archive $SCHEME $(marketing_version) ($(build_number))"
  snapshot_version_file
  # -allowProvisioningUpdates + the API key lets the automatic-signing archive
  # step refresh development profiles headlessly. Without the key it depends on
  # an Apple ID session inside Xcode, which silently vanishes on Xcode updates
  # ("No Accounts" / "No signing certificate 'Mac Installer Distribution'").
  # The version pair is passed explicitly for build-settings parity with the
  # Info.plist the pre-build script writes.
  logged archive asc xcode archive "${container[@]}" --scheme "$SCHEME" --configuration Release --clean \
    --archive-path "$ARCHIVE_PATH" --overwrite \
    --xcodebuild-flag=-destination --xcodebuild-flag="$DESTINATION" \
    --xcodebuild-flag="DEVELOPMENT_TEAM=$TEAM_ID" \
    --xcodebuild-flag="MARKETING_VERSION=$(marketing_version)" \
    --xcodebuild-flag="CURRENT_PROJECT_VERSION=$(build_number)" \
    --xcodebuild-flag=ONLY_ACTIVE_ARCH=NO \
    --xcodebuild-flag=-allowProvisioningUpdates \
    --xcodebuild-flag=-authenticationKeyPath --xcodebuild-flag="$ASC_PRIVATE_KEY_PATH" \
    --xcodebuild-flag=-authenticationKeyID --xcodebuild-flag="$ASC_KEY_ID" \
    --xcodebuild-flag=-authenticationKeyIssuerID --xcodebuild-flag="$ASC_ISSUER_ID" \
    --output json
  restore_version_file
  info "$ARCHIVE_PATH"
  verify_archive_contents
}

archive_and_export() {
  archive_only

  step "Export $PACKAGE_LABEL (manual signing, App Store profiles)"
  # If export fails, the useful log is the .xcdistributionlogs bundle path
  # printed by xcodebuild (IDEDistribution.standard.log), not the summary.
  logged export asc xcode export --archive-path "$ARCHIVE_PATH" "--$PACKAGE_KIND-path" "$PACKAGE_PATH" \
    --export-options "$EXPORT_OPTIONS" --overwrite --output json
  info "$PACKAGE_PATH"

  # The restore above must leave the tree exactly as committed.
  local after
  after=$(git -C "$REPO_ROOT" status --porcelain)
  [[ -z "$after" ]] || die "the build left the worktree dirty:
$after"
}

# REPO-SPECIFIC: sanity-check the archive's bundle structure (was the old
# Fastfile's verify_bundle!), then that the binary carries the committed
# version pair.
verify_archive_contents() {
  local app="$ARCHIVE_PATH/Products/Applications/$APP_NAME.app" rel missing=()
  for rel in Contents/MacOS/HomeClaw Contents/MacOS/homeclaw-cli Contents/Resources/mcp-server.js \
    Contents/Resources/openclaw/dist/index.js; do
    [[ -f "$app/$rel" ]] || missing+=("$rel")
  done
  for rel in Contents/Resources/macOSBridge.bundle Contents/Resources/openclaw; do
    [[ -d "$app/$rel" ]] || missing+=("$rel")
  done
  [[ ${#missing[@]} -eq 0 ]] || die "archive is missing: ${missing[*]}"
  info "Bundle has HomeClaw, homeclaw-cli, macOSBridge.bundle, mcp-server.js, openclaw/"

  # Without it HMHomeManager silently returns zero homes.
  codesign -d --entitlements :- "$app" 2>/dev/null | grep -q "com.apple.developer.homekit" \
    || die "HomeKit entitlement missing on the signed app."
  # Build 154 was rejected by App Store Connect with error 90296 ("App sandbox
  # not enabled") on homeclaw-cli: every executable in a Mac App Store bundle
  # must be sandboxed.
  codesign -d --entitlements :- "$app/Contents/MacOS/homeclaw-cli" 2>/dev/null \
    | grep -q "com.apple.security.app-sandbox" \
    || die "homeclaw-cli is not sandboxed; App Store Connect rejects the upload (error 90296)."
  info "HomeKit entitlement present; homeclaw-cli sandboxed"

  local plist="$app/Contents/Info.plist" built_version built_build
  built_version=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$plist")
  built_build=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$plist")
  [[ "$built_version" == "$(marketing_version)" && "$built_build" == "$(build_number)" ]] \
    || die "archive is $built_version ($built_build) but HEAD says $(marketing_version) ($(build_number))."
  info "Archived binary is $built_version ($built_build)"
}

validate_package() {
  step "Validate $PACKAGE_LABEL with Apple (altool --validate-app, no upload)"
  # altool finds AuthKey_<id>.p8 via API_PRIVATE_KEYS_DIR.
  API_PRIVATE_KEYS_DIR="$(dirname "$ASC_PRIVATE_KEY_PATH")" \
    asc xcode validate "--$PACKAGE_KIND" "$PACKAGE_PATH" --api-key "$ASC_KEY_ID" --api-issuer "$ASC_ISSUER_ID" --output json
  echo
}

# ─── ASC lookups (read-only) ─────────────────────────────────────────────

# App Store version id for a version string ("" when it doesn't exist yet).
version_id() {
  asc versions list --app "$APP_ID" --platform "$PLATFORM" --version "$1" --output json \
    | json_get 'd["data"][0]["id"] if d.get("data") else None'
}

version_state() {
  asc versions list --app "$APP_ID" --platform "$PLATFORM" --version "$1" --output json \
    | json_get '(d["data"][0]["attributes"].get("appStoreState") or d["data"][0]["attributes"].get("appVersionState")) if d.get("data") else None'
}

# Newest version still being prepared, else the live one: deliver's own
# precedence (use_live_version: false). See metadata-pull.
editable_or_live_version_id() {
  local prefer_live="$1"
  asc versions list --app "$APP_ID" --platform "$PLATFORM" --paginate --output json | "$PYTHON" -c '
import json, sys
prefer_live = sys.argv[1] == "true"
d = json.load(sys.stdin)["data"]
d.sort(key=lambda v: v["attributes"].get("createdDate") or "", reverse=True)
state = lambda v: v["attributes"].get("appStoreState") or v["attributes"].get("appVersionState") or ""
live = [v for v in d if state(v) == "READY_FOR_SALE"][:1]
edit = [v for v in d if state(v) not in ("READY_FOR_SALE", "REMOVED_FROM_SALE", "DEVELOPER_REMOVED_FROM_SALE", "REPLACED_WITH_NEW_VERSION")][:1]
pick = (live or edit) if prefer_live else (edit or live)
if pick:
    print(pick[0]["id"], pick[0]["attributes"]["versionString"], state(pick[0]))
' "$prefer_live"
}

# "<build id> <build number> <usesNonExemptEncryption>" for a version.
find_build() {
  local version="$1" number="${2:-}" args=()
  [[ -n "$number" ]] && args=(--build-number "$number")
  asc builds list --app "$APP_ID" --platform "$PLATFORM" --version "$version" \
    --processing-state VALID --sort -uploadedDate --limit 1 ${args[@]+"${args[@]}"} --output json \
    | json_get '" ".join(str(x) for x in (d["data"][0]["id"], d["data"][0]["attributes"]["version"], d["data"][0]["attributes"].get("usesNonExemptEncryption"))) if d.get("data") else None'
}

# ─── Subcommands ─────────────────────────────────────────────────────────

cmd_help() {
  cat <<EOF
Usage: scripts/release.sh <command> [options]

Build + TestFlight
  info                     Marketing version (nearest v* tag), build number, release tag, Xcode
  status [--build N]       App Store Connect: versions, recent builds, TestFlight groups (read-only)
  bump-build               Set $INFO_PLIST to the next build number and the tag's version
                           (local only). Commit it, tag v<version>+<build>, push, then beta.
  archive                  xcodegen + MCP build + archive only (no export, no upload)
  beta [--dry-run]         Guards, fresh App Store profiles, archive, export .pkg, then upload
                           to TestFlight "$INTERNAL_GROUP" and wait for processing. Stops there.
                           --dry-run stops after 'asc xcode validate' (nothing uploaded).
  profiles [--repair] [--prune] [--dry-run]
                           Check the App Store signing profiles; --repair regenerates any with
                           no ACTIVE copy, --prune deletes stale sigh copies. beta never does.
  external [--build N] [--version V] [--groups "A,B"] [--dry-run]
                           Add an uploaded build to "$EXTERNAL_GROUP", set What to Test,
                           notify testers, submit for beta review. Defaults to the project's
                           version + build.

App Store (Mac App Store listing, platform $PLATFORM)
  metadata [--dry-run]     Push appstore/metadata to the project's App Store version
  metadata-pull [--live]   Overwrite appstore/metadata with what ASC holds (editable version
                           first, like deliver; --live reads the shipped listing)
  release [--version V] [--build N] [--notes-file F | --notes TEXT] [--notes-only]
          [--skip-screenshots] [--auto-release] [--dry-run]
                           Ensure the version exists (manual release after approval unless
                           --auto-release), push metadata and screenshots, attach the newest
                           VALID build (or N), submit for App Review. --notes-only pushes only
                           "What's New" and leaves the live listing alone.
  submit [--version V] [--build N] [--dry-run]
                           Submit an existing build for review; no metadata push, no version create

Screenshots
  screenshots              Capture raw shots with the Catalyst UI tests (scripts/screenshots.sh)
  frame                    Gradient + window + tagline via scripts/frame_screenshots.sh
  upload-screenshots [--dry-run] [--allow-partial]
                           Replace the App Store desktop screenshot set with appstore/framed

Environment
  TF_CHANGELOG             TestFlight What to Test (default: metadata $LOCALE/release_notes.txt)
  DEVELOPER_DIR, XCODE_APP Pick an Xcode for this run (default: the one .xcode-version pins)
EOF
}

cmd_info() {
  local tag
  tag=$(git -C "$REPO_ROOT" tag --points-at HEAD --list 'v*' | tr '\n' ' ')
  bold "$APP_NAME ($APP_ID)"
  info "Marketing version: $(marketing_version) (nearest v* tag)"
  info "Build number:      $(build_number) ($INFO_PLIST; plist version $(plist_value CFBundleShortVersionString))"
  info "Local counter:     $(cat "$REPO_ROOT/.build-number" 2>/dev/null || echo none) (.build-number)"
  info "HEAD tag:          ${tag:-none}"
  info "Nearest tag:       $(git -C "$REPO_ROOT" describe --tags --abbrev=0 --match 'v*' 2>/dev/null || echo none)"
  resolve_toolchain
}

cmd_status() {
  local build=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --build) build="$2"; shift ;;
      *) die "unknown status option: $1" ;;
    esac
    shift
  done
  load_credentials
  read_only
  info "Team: ${TEAM_ID:-none} (from ${TEAM_ID_SOURCE:-no variable})"
  step "App Store versions"
  asc versions list --app "$APP_ID" --platform "$PLATFORM" --limit 5 --output table
  if [[ -n "$build" ]]; then
    step "Build $build"
    asc builds list --app "$APP_ID" --platform "$PLATFORM" --build-number "$build" --output table
  else
    step "Recent builds"
    asc builds list --app "$APP_ID" --platform "$PLATFORM" --sort -uploadedDate --limit 5 --output table
  fi
  step "TestFlight groups"
  asc testflight groups list --app "$APP_ID" --output table
}

# REPO-SPECIFIC: the old lanes computed the next build as `.build-number` + 1
# at archive time and committed the bumped Info.plist after the upload. The
# number now lands in a commit first: next = one past the highest of the
# committed plist, the local `.build-number` counter, and (when credentials
# are available) App Store Connect's highest uploaded build.
cmd_bump_build() {
  local current counter remote="" next version
  current=$(build_number)
  counter=$(tr -d '[:space:]' <"$REPO_ROOT/.build-number" 2>/dev/null || echo 0)
  next=$(( current > counter ? current : counter ))
  if (load_credentials) >/dev/null 2>&1; then
    load_credentials
    read_only
    remote=$(asc builds next-build-number --app "$APP_ID" --platform "$PLATFORM" --output json \
      | json_get 'd.get("latestObservedBuildNumber")' || true)
    [[ -n "$remote" && "$remote" -gt "$next" ]] && next="$remote"
  else
    warn "no App Store Connect credentials; not checking uploaded build numbers."
  fi
  next=$((next + 1))
  version=$(marketing_version)
  /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $next" -c "Set :CFBundleShortVersionString $version" "$REPO_ROOT/$INFO_PLIST"
  bold "$INFO_PLIST -> $version ($next)"
  info "plist was $current, .build-number $counter, App Store Connect highest ${remote:-unknown}"
  info "Next: git commit -m \"chore(release): build $next\" $INFO_PLIST"
  info "      git tag -a v$version+$next -m \"Release v$version build $next\" && git push && git push origin v$version+$next"
}

# REPO-SPECIFIC: the old `archive` lane (archive only, open it in Organizer).
cmd_archive() {
  load_credentials
  read_only
  [[ -n "$TEAM_ID" ]] || die "no team id (set one of: $TEAM_ID_VARS)."
  step "Preflight"
  resolve_toolchain
  check_release_tag soft
  prepare
  archive_only
  bold "Archive: $ARCHIVE_PATH"
  info "Open in Organizer: open '$ARCHIVE_PATH'"
}

cmd_beta() {
  local dry_run=false
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --dry-run) dry_run=true ;;
      *) die "unknown beta option: $1" ;;
    esac
    shift
  done
  load_credentials
  $dry_run && read_only
  [[ -n "$TEAM_ID" ]] || die "no team id (set one of: $TEAM_ID_VARS)."

  step "Preflight"
  require_clean_tree
  resolve_toolchain
  require_release_xcode
  if $dry_run; then check_release_tag soft; else check_release_tag hard; fi
  prepare

  step "Provisioning profiles"
  refresh_profiles
  archive_and_export
  validate_package

  if $dry_run; then
    bold "Dry run complete: $PACKAGE_PATH built, exported and validated. Nothing uploaded."
    return
  fi

  step "Upload to TestFlight ($INTERNAL_GROUP) and wait for processing"
  local package_args=("--$PACKAGE_KIND" "$PACKAGE_PATH")
  # A .pkg carries no metadata asc can read, so it needs the pair spelled out.
  [[ "$PACKAGE_KIND" == "pkg" ]] \
    && package_args+=(--version "$(marketing_version)" --build-number "$(build_number)" --platform "$PLATFORM")
  asc publish testflight --app "$APP_ID" "${package_args[@]}" --group "$INTERNAL_GROUP" \
    --test-notes "$(tester_notes)" --locale "$LOCALE" --wait --output json
  echo
  bold "Uploaded $(marketing_version) ($(build_number)) to TestFlight. Not submitted for App Review."
}

cmd_external() {
  local dry_run=false version="" build="" groups="$EXTERNAL_GROUP"
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --dry-run) dry_run=true ;;
      --build) build="$2"; shift ;;
      --version) version="$2"; shift ;;
      --groups) groups="$2"; shift ;;
      *) die "unknown external option: $1" ;;
    esac
    shift
  done
  load_credentials
  $dry_run && read_only
  version="${version:-$(marketing_version)}"
  build="${build:-$(build_number)}"

  step "Distribute $SCHEME $version ($build) to $groups"
  local found build_id
  found=$(find_build "$version" "$build")
  [[ -n "$found" ]] || die "no VALID build $build for version $version on App Store Connect."
  build_id="${found%% *}"
  info "Build id $build_id"
  if $dry_run; then
    info "Would add to: $groups, set What to Test, notify testers, submit for beta review:"
    tester_notes | sed 's/^/      | /'
    echo
    return
  fi
  # Beta review only triggers the first time a marketing version goes external.
  asc publish testflight --app "$APP_ID" --build-id "$build_id" --group "$groups" \
    --test-notes "$(tester_notes)" --locale "$LOCALE" --wait --notify --submit --confirm --output json
  echo
}

# ASC's current metadata for one version, written in the same fastlane layout
# as appstore/metadata. `asc migrate export` covers the localized .txt files;
# copyright and categories are read separately because migrate skips them.
export_remote_metadata() {
  local vid="$1" dir="$2" category
  asc migrate export --app "$APP_ID" --version-id "$vid" --output-dir "$dir" --output json >/dev/null
  mkdir -p "$dir/metadata"
  asc versions list --app "$APP_ID" --platform "$PLATFORM" --paginate --output json \
    | json_get 'next((v["attributes"].get("copyright") for v in d["data"] if v["id"] == "'"$vid"'"), None)' \
    >"$dir/metadata/copyright.txt"
  for category in primary secondary; do
    asc apps info relationships "$category-category" --app "$APP_ID" --output json \
      | json_get 'd["data"].get("id") or None' >"$dir/metadata/${category}_category.txt"
    # An unset category comes back empty; don't invent an empty file for it.
    [[ -s "$dir/metadata/${category}_category.txt" && -n "$(tr -d '[:space:]' <"$dir/metadata/${category}_category.txt")" ]] \
      || mv -f "$dir/metadata/${category}_category.txt" "$dir/.unset-${category}_category.txt"
  done
}

# Unified diff of a local metadata tree against ASC (remote), ignoring
# trailing whitespace. Returns 0 when they match. A partial tree (--notes-only)
# is compared file by file, so absent files don't read as deletions.
diff_metadata() {
  local vid="$1" local_dir="$2" tmp changes
  mkdir -p "$ARTIFACTS"
  tmp=$(mktemp -d "$ARTIFACTS/metadata-diff.XXXXXX")
  export_remote_metadata "$vid" "$tmp"
  # A push only uploads the files it has, so a file only on ASC is no change.
  changes=$(cd "$tmp" && diff -ru -b metadata "$local_dir" | grep -v '^Only in metadata' || true)
  if [[ -z "$changes" ]]; then
    info "$(basename "$(dirname "$local_dir")")/metadata matches App Store Connect (no changes to push)"
    return 0
  fi
  info "Changes a push would make (--- ASC, +++ local):"
  printf '%s\n' "$changes" | sed 's/^/      /'
  return 1
}

# Pushes a metadata tree (fastlane layout, default appstore/metadata) to one
# App Store version. Every .txt is uploaded: description, keywords, name,
# subtitle, URLs, release notes, review information, copyright, categories.
# Run metadata-pull first if ASC may have drifted. A dry run shows the file
# list asc would import and the diff against ASC.
push_metadata() {
  local vid="$1" dry_run="$2" root="${3:-$APPSTORE_DIR}"
  local meta="$root/metadata"
  if $dry_run; then
    asc migrate import --app "$APP_ID" --version-id "$vid" --fastlane-dir "$root" \
      --skip-screenshots --skip-previews --dry-run --output table
    diff_metadata "$vid" "$meta" || true
    return
  fi
  asc migrate import --app "$APP_ID" --version-id "$vid" --fastlane-dir "$root" \
    --skip-screenshots --skip-previews --confirm --output table
  if [[ -f "$meta/copyright.txt" ]]; then
    asc versions update --version-id "$vid" --copyright "$(tr -d '\n' <"$meta/copyright.txt")" --output json >/dev/null
    info "copyright.txt pushed"
  fi
  if [[ -f "$meta/primary_category.txt" ]]; then
    local args=(--primary "$(tr -d '[:space:]' <"$meta/primary_category.txt")")
    [[ -f "$meta/secondary_category.txt" ]] \
      && args+=(--secondary "$(tr -d '[:space:]' <"$meta/secondary_category.txt")")
    asc categories set --app "$APP_ID" "${args[@]}" --output json >/dev/null
    info "categories pushed"
  fi
}

cmd_metadata() {
  local dry_run=false version=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --dry-run) dry_run=true ;;
      --version) version="$2"; shift ;;
      *) die "unknown metadata option: $1" ;;
    esac
    shift
  done
  load_credentials
  $dry_run && read_only
  version="${version:-$(marketing_version)}"
  local vid state
  vid=$(version_id "$version")
  [[ -n "$vid" ]] || die "App Store version $version does not exist yet (\`release\` creates it)."
  state=$(version_state "$version")
  step "Metadata -> App Store version $version ($state)"
  [[ "$state" == "READY_FOR_SALE" ]] && warn "$version is live; App Store Connect only accepts edits on a version being prepared."
  push_metadata "$vid" "$dry_run"
}

# `appstore/metadata/` is the version-controlled source of truth that
# `release` pushes. This pulls the other direction: it overwrites the local
# files with what ASC currently holds, so a hand-edit made in the web UI lands
# as a reviewable diff instead of silently drifting.
#
# Edit-first, matching deliver's own default (use_live_version: false). While
# a version is being prepared, the edits worth capturing live on that upcoming
# version; reading the live listing instead would overwrite them with the
# already-shipped copy, and the next `release` would push that stale text back
# over the new version. --live deliberately reads the shipped listing.
cmd_metadata_pull() {
  local live=false
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --live) live=true ;;
      *) die "unknown metadata-pull option: $1" ;;
    esac
    shift
  done
  load_credentials
  read_only
  local picked vid version state tmp
  picked=$(editable_or_live_version_id "$live")
  [[ -n "$picked" ]] || die "no editable or live App Store version."
  read -r vid version state <<<"$picked"
  step "Reading App Store version $version ($state)"
  mkdir -p "$ARTIFACTS"
  tmp=$(mktemp -d "$ARTIFACTS/metadata-pull.XXXXXX")
  export_remote_metadata "$vid" "$tmp"
  mkdir -p "$METADATA_DIR"
  rsync -a "$tmp/metadata/" "$METADATA_DIR/"
  info "Synced -> $METADATA_DIR"
  warn "review \`git diff appstore/metadata\` before committing."
}

# Shared by release and submit. deliver's submission_information answered the
# export-compliance question on every submission; the Info.plist carries
# ITSAppUsesNonExemptEncryption=NO, so builds normally arrive answered and
# this only fills a gap.
ensure_encryption_answer() {
  local build_id="$1" answer="$2" dry_run="$3"
  if [[ "$answer" == "False" || "$answer" == "false" ]]; then
    info "Export compliance: already answered (no non-exempt encryption)"
  elif $dry_run; then
    info "Would set usesNonExemptEncryption=false on build $build_id"
  else
    asc builds update --build-id "$build_id" --uses-non-exempt-encryption=false --output json >/dev/null
    info "Export compliance: set usesNonExemptEncryption=false"
  fi
}

# REPO-SPECIFIC release options (the old `release` / `release_build` lanes).
RELEASE_NOTES=""          # --notes-file / --notes: "What's New" for this submission
RELEASE_NOTES_ONLY=false  # --notes-only: push only "What's New" (was skip_metadata:true)
RELEASE_SCREENSHOTS=false # release replaces the screenshot set unless --skip-screenshots

# The metadata tree a release pushes. Default: appstore itself. With notes
# given, a staged copy whose en-US/release_notes.txt carries them. With
# --notes-only, a tree holding just that file: the importer only uploads
# fields whose files exist, so every other field on the live listing is left
# alone (deliver's skip_metadata:true would have dropped "What's New" too).
release_metadata_root() {
  if [[ -z "$RELEASE_NOTES" ]] && ! $RELEASE_NOTES_ONLY; then
    printf '%s\n' "$APPSTORE_DIR"
    return
  fi
  local root
  mkdir -p "$ARTIFACTS"
  root=$(mktemp -d "$ARTIFACTS/release-metadata.XXXXXX")
  mkdir -p "$root/metadata/$LOCALE"
  $RELEASE_NOTES_ONLY || rsync -a "$METADATA_DIR/" "$root/metadata/"
  if [[ -n "$RELEASE_NOTES" ]]; then
    printf '%s\n' "$RELEASE_NOTES" >"$root/metadata/$LOCALE/release_notes.txt"
  else
    cp "$METADATA_DIR/$LOCALE/release_notes.txt" "$root/metadata/$LOCALE/release_notes.txt"
  fi
  printf '%s\n' "$root"
}

submit_for_review() {
  local version="$1" build="$2" dry_run="$3" push="$4"
  local vid state found build_id build_num answer
  vid=$(version_id "$version")

  step "App Store version $version"
  if [[ -n "$vid" ]]; then
    state=$(version_state "$version")
    info "Version $version is $state"
    # asc's own dry run doesn't look at state. A live or in-review version
    # can't take metadata edits or a new submission, so stop before sending
    # anything.
    case "$state" in
      READY_FOR_SALE | READY_FOR_DISTRIBUTION | WAITING_FOR_REVIEW | IN_REVIEW | PENDING_DEVELOPER_RELEASE)
        if $dry_run; then
          warn "$version is $state; a real run would refuse. Tag the next version (v<X.Y.Z>) for the next release."
        else
          die "$version is $state and can't be submitted again. Tag the next version (v<X.Y.Z>) for the next release."
        fi
        ;;
    esac
    if $push; then
      if $dry_run; then
        info "Would set release type $RELEASE_TYPE"
      else
        asc versions update --version-id "$vid" --release-type "$RELEASE_TYPE" --output json >/dev/null
        info "Release type $RELEASE_TYPE"
      fi
    fi
  elif ! $push; then
    die "App Store version $version does not exist (\`release\` creates it)."
  elif $dry_run; then
    info "Would create App Store version $version (release type $RELEASE_TYPE)"
  else
    asc versions create --app "$APP_ID" --version "$version" --platform "$PLATFORM" \
      --release-type "$RELEASE_TYPE" --if-exists skip --output json >/dev/null
    vid=$(version_id "$version")
    info "Created version $version"
  fi

  if $push; then
    step "Metadata -> $version"
    local root
    root=$(release_metadata_root)
    [[ -n "$(tr -d '[:space:]' <"$root/metadata/$LOCALE/release_notes.txt" 2>/dev/null)" ]] \
      || die "missing \"What's New\": $root/metadata/$LOCALE/release_notes.txt is empty (or pass --notes-file / --notes)."
    if [[ -n "$vid" ]]; then
      push_metadata "$vid" "$dry_run" "$root"
    else
      info "Would push $root/metadata once the version exists"
    fi
    if $RELEASE_SCREENSHOTS; then
      if [[ -n "$vid" ]]; then
        local mode=()
        $dry_run && mode=(--dry-run)
        cmd_upload_screenshots --version "$version" ${mode[@]+"${mode[@]}"}
      else
        info "Would replace the screenshot sets from appstore/framed once the version exists"
      fi
    fi
  fi

  step "Build"
  found=$(find_build "$version" "$build")
  [[ -n "$found" ]] || die "no VALID build${build:+ $build} for version $version on App Store Connect."
  read -r build_id build_num answer <<<"$found"
  info "Build $build_num ($build_id)"
  ensure_encryption_answer "$build_id" "$answer" "$dry_run"

  step "Submit $version ($build_num) for App Review"
  if [[ -z "$vid" ]]; then
    info "Would attach build $build_num and submit (version not created in a dry run)"
  elif $dry_run; then
    asc review submit --app "$APP_ID" --version-id "$vid" --build-id "$build_id" --platform "$PLATFORM" --dry-run --output json
    echo
  else
    asc review submit --app "$APP_ID" --version-id "$vid" --build-id "$build_id" --platform "$PLATFORM" --confirm --output json
    echo
    if [[ "$RELEASE_TYPE" == "MANUAL" ]]; then
      bold "Submitted $version ($build_num) for App Review; after approval it waits in Pending Developer Release."
    else
      bold "Submitted $version ($build_num) for App Review; releases automatically after approval."
    fi
    info "Track at https://appstoreconnect.apple.com/apps/$APP_ID/distribution"
  fi
}

parse_submit_args() {
  SUBMIT_DRY_RUN=false SUBMIT_VERSION="" SUBMIT_BUILD=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --dry-run) SUBMIT_DRY_RUN=true ;;
      --version) SUBMIT_VERSION="$2"; shift ;;
      --build) SUBMIT_BUILD="$2"; shift ;;
      # REPO-SPECIFIC (release only; see cmd_release).
      --notes) RELEASE_NOTES="$2"; shift ;;
      --notes-file) [[ -f "$2" ]] || die "notes file not found: $2"; RELEASE_NOTES="$(<"$2")"; shift ;;
      --notes-only) RELEASE_NOTES_ONLY=true ;;
      --skip-screenshots) RELEASE_SCREENSHOTS=false ;;
      --auto-release) RELEASE_TYPE="AFTER_APPROVAL" ;;
      *) die "unknown option: $1" ;;
    esac
    shift
  done
}

# The old `release` lane built, uploaded and submitted in one go; that is now
# `beta` then `release`. The old `release_build` lane is `release --build N`.
# Both old lanes replaced the screenshot set by default, so this does too
# (--skip-screenshots when appstore/framed is stale relative to the build).
cmd_release() {
  RELEASE_SCREENSHOTS=true
  parse_submit_args "$@"
  load_credentials
  $SUBMIT_DRY_RUN && read_only
  submit_for_review "${SUBMIT_VERSION:-$(marketing_version)}" "$SUBMIT_BUILD" "$SUBMIT_DRY_RUN" true
}

cmd_submit() {
  parse_submit_args "$@"
  if [[ -n "$RELEASE_NOTES" ]] || $RELEASE_NOTES_ONLY; then
    die "submit pushes no metadata; use release --notes-only."
  fi
  load_credentials
  $SUBMIT_DRY_RUN && read_only
  submit_for_review "${SUBMIT_VERSION:-$(marketing_version)}" "$SUBMIT_BUILD" "$SUBMIT_DRY_RUN" false
}

cmd_screenshots() {
  resolve_toolchain
  "$REPO_ROOT/scripts/screenshots.sh" "$@"
}

# REPO-SPECIFIC: HomeClaw's shots are Mac windows on a gradient with a
# tagline, not device bezels, so framing stays with scripts/frame_screenshots.sh
# (ImageMagick) rather than the frameit port other apps use.
cmd_frame() {
  SRC_DIR="$SHOTS_DIR/$LOCALE" OUT_DIR="$FRAMED_DIR/$LOCALE" "$REPO_ROOT/scripts/frame_screenshots.sh" "$@"
}

# Stages framed PNGs into one directory per App Store display type (by pixel
# size) and replaces each set. --replace deletes the whole existing set first,
# so a partial local set would silently drop screenshots from the listing.
# Every panel (titles in title.strings, or else every raw capture in
# appstore/screenshots) must therefore have a framed shot per display type
# unless --allow-partial is passed.
cmd_upload_screenshots() {
  local dry_run=false allow_partial=false version=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --dry-run) dry_run=true ;;
      --allow-partial) allow_partial=true ;;
      --version) version="$2"; shift ;;
      *) die "unknown upload-screenshots option: $1" ;;
    esac
    shift
  done
  load_credentials
  $dry_run && read_only
  version="${version:-$(marketing_version)}"
  [[ -n "$(version_id "$version")" ]] || die "App Store version $version does not exist yet (\`release\` creates it)."
  local src="$FRAMED_DIR/$LOCALE" stage="$ARTIFACTS/screenshots"
  compgen -G "$src/*.png" >/dev/null || die "no framed screenshots in $src (run: scripts/release.sh frame)"

  "$PYTHON" - "$src" "$stage" "$SCREENSHOT_TYPES" "$SHOTS_DIR/$LOCALE" "$allow_partial" <<'PY'
import re, shutil, sys
from pathlib import Path
from PIL import Image
src, stage, types, raw, allow_partial = Path(sys.argv[1]), Path(sys.argv[2]), sys.argv[3], Path(sys.argv[4]), sys.argv[5] == "true"
by_size = dict(t.split("=") for t in types.split())
shutil.rmtree(stage, ignore_errors=True)  # our own staging dir under .asc/
strings = raw / "title.strings"
if strings.exists():
    titles = re.findall(r'^"([^"]+)"\s*=', strings.read_text(), re.M)
else:
    titles = sorted(p.stem for p in raw.glob("*.png"))
found = {}
for png in sorted(src.glob("*.png")):
    w, h = Image.open(png).size
    kind = by_size.get(f"{w}x{h}")
    if not kind:
        sys.exit(f"{png.name}: {w}x{h} matches no display type in SCREENSHOT_TYPES")
    (stage / kind).mkdir(parents=True, exist_ok=True)
    shutil.copy2(png, stage / kind / png.name)
    found.setdefault(kind, []).append(png.name)
missing = []
for kind, names in sorted(found.items()):
    print(f"    {kind}: {len(names)} screenshot(s)")
    for title in titles:
        if not any(title in n for n in names):
            missing.append(f"{kind} {title}")
if missing:
    msg = "missing framed screenshots (the upload replaces the whole set): " + ", ".join(missing)
    if allow_partial:
        print("warning: " + msg, file=sys.stderr)
    else:
        sys.exit(msg + "\nCapture them (see appstore/MANUAL_SCREENSHOTS.md) or pass --allow-partial.")
PY

  local dir kind mode=(--confirm)
  $dry_run && mode=(--dry-run)
  for dir in "$stage"/*/; do
    kind=$(basename "$dir")
    step "Screenshots $kind -> $version $LOCALE ($($dry_run && echo dry run || echo replace))"
    asc screenshots upload --app "$APP_ID" --version "$version" --platform "$PLATFORM" --locale "$LOCALE" \
      --path "$dir" --device-type "$kind" --replace "${mode[@]}" --output table
  done
}

main() {
  local cmd="${1:-help}"
  [[ $# -gt 0 ]] && shift
  cd "$REPO_ROOT"
  case "$cmd" in
    help|-h|--help) cmd_help ;;
    info) cmd_info ;;
    status) cmd_status "$@" ;;
    bump-build) cmd_bump_build ;;          # REPO-SPECIFIC
    archive) cmd_archive ;;                # REPO-SPECIFIC
    beta) cmd_beta "$@" ;;
    profiles) cmd_profiles "$@" ;;
    external) cmd_external "$@" ;;
    metadata) cmd_metadata "$@" ;;
    metadata-pull) cmd_metadata_pull "$@" ;;
    release) cmd_release "$@" ;;
    submit) cmd_submit "$@" ;;
    screenshots) cmd_screenshots "$@" ;;
    frame) cmd_frame "$@" ;;
    upload-screenshots) cmd_upload_screenshots "$@" ;;
    *) cmd_help >&2; die "unknown command: $cmd" ;;
  esac
}

main "$@"
